import lexer

# blm bisa handle multiline comment, []
rules = [
    (r'[\s\t]+', None),
    (r'#[^\n]*', None),
    (r'\"\"\"[\w\W\n+]*\"\"\"', None),
    (r'\'\'\'[\w\W\n+]*\'\'\'', None),
    (r'[\+\-]?[0-9]+', "NUM"),
    (r'[\+\-]?[0-9]+\.[0-9]+', "NUM"),
    (r'\:=',"EQ"),
    (r'\==',"ISEQ"),
    (r'->',"ARROW"),
    (r'\(',"LP"),
    (r'\)',"RP"), #rigth parantheses
    (r'\;', "SC"), #semicolon
    (r'\:', "COLON"),
    (r'<<',"BLS"),
    (r'>>',"BRS"),
    (r'//',"DIV"),
    (r'/',"DIV"),
    (r'<>',"NEQ"),
    (r'<=',"LEQ"),
    (r'<',"LESS"),
    (r'>=',"GEQ"),
    (r'>',"GREATER"),
    (r'=',"EQ"), #
    (r'!=',"NEQ"),
    (r'\-=',"MINEQ"),
    (r'/=',"DIVEQ"), 
    (r'\*=',"MULEQ"),    
    (r'\%=',"MODEQ"),
    (r'\*\*=',"POWEREQ"),
    (r'//=',"DIVEQ"),
    (r'\+=',"ADDEQ"), 
    (r'!=',"NEQ"),
    (r'\+',"ADD"),
    (r'-',"SUB"),
    (r'\*',"MUL"),
    (r'\.',"POINT"), 
    (r'\,',"COMMA"),
    (r'\%',"MOD"), 
    (r'\*\*',"POWER"),
    (r'\&',"AND"),
    (r'\|',"AND"),
    (r'\^',"XOR"),
    (r'\~',"NOT"),
    (r'\[',"LAB"), #left angle bracket 
    (r'\]',"RAB"), #right angle bracket
    (r'\{',"LCB"), #left curly bracket 
    (r'\}',"RCB"), #right curly bracket
    (r'\band\b',"AND"),
    (r'\bor\b', "OR"),
    (r'\bnot\b',"NOT"),
    (r'\bif\b', "IF"),
    (r'\bthen\b',"THEN"),
    (r'\belse\b', "ELSE"),
    (r'\bwhile\b',"WHILE"),
    (r'\bdo\b',"DO"),
    (r'\bend\b',"END"),
    (r'\bFalse\b',"FALSE"),
    (r'\bclass\b', "CLASS"),
    (r'\bis\b',"IS"),
    (r'\bcontinue\b',"CONTINUE"),
    (r'\bfor\b',"FOR"),
    (r'\bTrue\b',"TRUE"),
    (r'\bdef\b', "DEF"),
    (r'\bfrom\b',"FROM"),
    (r'\bwith\b',"WITH"),
    (r'\bas\b',"AS"),
    (r'\belif\b',"ELIF"),
    (r'\bimport\b',"IMPORT"),
    (r'\bpass\b', "PASS"),
    (r'\bbreak\b',"BREAK"),
    (r'\bin\b',"IN"),
    (r'\braise\b',"RAISE"),
    (r'\breturn\b',"RETURN"),
    (r'\bNone\b',"NONE"),
    (r'\bdict\b',"TYPE"),
    (r'\bint\b',"TYPE"),
    (r'\bstr\b',"TYPE"),
    (r'\bfloat\b',"TYPE"),
    (r'\bcomplex\b',"TYPE"),
    (r'\blist\b',"TYPE"),
    (r'\btuple\b',"TYPE"),
    (r'\"[^\n]*\"', "STRING"),
    (r'\'[^\n]*\'', "STRING"),
    (r'[A-Za-z_][A-Za-z0-9_]*', "ID"),
    (r'\_\_[a-z]+\_\_*', "ID"),
    (r'\"', "QMARK"),
    (r'\'', "SQMARK"),
]

def imp_lex(characters):
    return lexer.lex(characters, rules)
